language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to run tests
script:
  - coverage run --source=grpc_django manage.py test
before_install:
  - pip install -r requirements.txt
  - pip install coveralls
after_success:
  coveralls
